### ISSUE TITLE
Can I run minibar without modifying fastq header?

### ISSUE THREAD

**Issue by amsy29** [calacademy-research/minibar#3]
Is it possible to run the minibar.py script without adding the match hit info and sample id at the end of the fastq file header?

**Comment by jbh-cas** [comment]
Not as an option in the program but you can do so after the fact with a simple script -- not as convenient as an option I know. For fasta files, e.g. sample.fasta, you could run this awk script.

`awk '/^>/{sub(" [Hh].([0-9,]*).*", "")}{print}' sample.fasta >clnd_sample.fasta`

This relies on the fasta header lines starting with >

For fastq files, e.g., sample.fastq, you could run this awk script

`awk '{hdr=(0==(FNR-1)%4)}hdr{sub(" [Hh].([0-9,]*).*","")}{print}' sample.fastq >clnd_sample.fastq`

This relies on the header line of fastq records being on the first line and and every four lines thereafter.

After you are sure the script is giving you what you want, use mv to rename the cleaned file to the original, leaving a file with the original name without the fastq or fasta header additions.

`mv clnd_sample.fastq sample.fastq  # renames the new file to old, deleting original content`
