### ISSUE TITLE
Quality score length mismatch

### ISSUE THREAD

**Issue by mitja-remus-emsermann** [calacademy-research/minibar#4]
Hi, thanks for building this tool - it does exactly what I was looking for. I am trying to sort ONT reads that have pcr barcodes on their ends. After sorting, downstream tools claim that the quality score length does not match the read length. The reads were called by guppy running on the latest version of MinKnow on windows 10. I am running minibar on MacOS 11.2.

I hope you can help, thanks, Mitja

**Comment by jbh-cas** [comment]
I don't have enough information to be of much help. Fastq files should have records of 4 lines each:
   (1) a header line beginning with @ then (2) a sequence line followed by (3) a line beginning with + and finally (4) the quality score line
The length of the 2nd and 4th
lines are expected to be the same. You can run this command line substituting your fastq file name for test_reads.fq and it will print out records where this is not the case.
$ awk
'0==((NR-1)%4){if(NR>1)printf("\n");printf("%s",$1);next}{printf("\t%d", length($0))}' test_reads.fq | awk '$2 != $4'
This is making a line with the header,  followed by the lengths of the 2nd, 3rd and 4th lines. You can pipe to
less to see what the output looks like
$ awk '0==((NR-1)%4){if(NR>1)printf("\n");printf("%s",$1);next}{printf("\t%d", length($0))}' test_reads.fq |awk '$2==$4' |
less
This might help to figure out which files and records are having length issues.
--Jim Henderson
---------------------------- Original Message ----------------------------

Subject: [calacademy-research/minibar] Quality score length mismatch (#4)

From: "mitja-remus-emsermann" 

Date: Thu, February 4, 2021 12:18 am

To: "calacademy-research/minibar" 

Cc: "Subscribed" 

--------------------------------------------------------------------------




 
Hi, thanks for building this tool - it does exactly what I was looking for. I am trying to sort ONT reads that have pcr barcodes on their ends. After sorting,
downstream tools claim that the quality score length does not match the read length. The reads were called by guppy running on the latest version of MinKnow on windows 10. I am running minibar on MacOS 11.2.
I hope you can help, thanks, Mitja—

**Comment by mitja-remus-emsermann** [comment]
Hi Jim,

thanks for your response. I just tried to reproduce the problem again without any luck, to reads and quality information seem to line up again. I had rebooted my machine in the meantime, maybe that fixed it. Looking forward to using your tool to sort my reads.

Sorry for the hassle. Kind regards, Mitja
